Bank_Apps/CustomerWebApp/Models/TransferMoney.cs
using System.ComponentModel.DataAnnotations;
namespace CustomerWebApp.Models
{
    public class TransferMoney
    {
        [Key]
        public int SerialNumber { get; set; }
        public int FromAccountNumber { get; set; }
        public int ToAccountNumber { get; set; }
        public int Amount { get; set; }
        public string TransactionId { get; set; }   

        public TransferMoney()
        {

        }
    }
}

Bank_Apps/CustomerWebApp/Controllers/LoginCustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CustomerWebApp.Data;
using CustomerWebApp.Models;
using Microsoft.CodeAnalysis;

namespace CustomerWebApp.Controllers
{
    public class LoginCustomersController : Controller
    {
        private readonly CustomerWebAppContext _context;
        private readonly BankAccountDBContext _AccountDetailscontext= new BankAccountDBContext();
        private double balance;

        public LoginCustomersController(CustomerWebAppContext context)
        {
            _context = context;
        }

        // GET: LoginCustomers
        public async Task<IActionResult> Index()
        {
              return View(await _context.LoginCustomer.ToListAsync());
        }

        // GET: LoginCustomers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.LoginCustomer == null)
            {
                return NotFound();
            }

            var loginCustomer = await _context.LoginCustomer
                .FirstOrDefaultAsync(m => m.SerialNumber == id);
            if (loginCustomer == null)
            {
                return NotFound();
            }

            return View(loginCustomer);
        }
        // GET: LoginCustomers/Create/Login/FindAccountNumber
        public IActionResult FindAccountNumber()
        {

            return View();
        }
        // POST: LoginCustomers/Create/Login/FindAccountNumber
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> FindAccountNumber([Bind("SerialNumber,AccountNumber,InternetBankingId,InternetBankingPassword")] LoginCustomer loginCustomer)
        {
            int accNumber = 0;
            //if (id == 0 || _context.LoginCustomer == null)
            //{
            //    return NotFound();
            //}
            int id = loginCustomer.InternetBankingId;
            string password=loginCustomer.InternetBankingPassword;

            var loginCustomer1 = await _context.LoginCustomer
                .FirstOrDefaultAsync(m => m.InternetBankingId == id && m.InternetBankingPassword==password);
            
            if (loginCustomer1 == null)
            {
                return NotFound();
            }
            else
            {
                TempData["AccountNumber"] = loginCustomer1.AccountNumber;
            }
            

            return View("FindAccountNumber",  _AccountDetailscontext.Accounts.Where(j => j.AccountNumber == loginCustomer1.AccountNumber).FirstOrDefault());
            //return View("FindAccountNumber",await _context.Account.Where(j=> j.AccountNumber == loginCustomer1.AccountNumber).ToListAsync());

        }

        // GET: LoginCustomers/Create/Login/GetBankBalance
        public IActionResult GetBankBalance()
        {
            return View();
        }

        // GET: LoginCustomers/Create/Login/GetBankBalance
        public IActionResult TransferMoneyIntra()
        {
            return View();
        }
        // POST: LoginCustomers/Create/Login/GetBankBalance
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> TransferMoneyIntra([Bind("AccountNumber", "FirstName", "LastName", "Ifsc", "MobileNumber")] Account loginCustomer)
        {
            //int accNumber = 0;
            //int accNum = loginCustomer.AccountNumber;
            int accNumber = Convert.ToInt32(TempData["AccountNumber"]);

            var loginCustomer1 = await _context.LoginCustomer
                .FirstOrDefaultAsync(m => m.AccountNumber == accNumber);

            if (loginCustomer1 == null)
            {
                return NotFound();
            }
            else
            {
                accNumber = loginCustomer1.AccountNumber;
            }

            TempData["BankBalance"] = _AccountDetailscontext.BankBalanceClasses.Where(j => j.AccountNumber == loginCustomer1.AccountNumber).FirstOrDefault().Balance.ToString();

            return View("GetBankBalance", _AccountDetailscontext.Accounts.Where(j => j.AccountNumber == loginCustomer1.AccountNumber).FirstOrDefault());
            //return View("FindAccountNumber",await _context.Account.Where(j=> j.AccountNumber == loginCustomer1.AccountNumber).ToListAsync());

        }
        // GET: LoginCustomers/LogIn
        public IActionResult LogIn()
        {
            return View("Create");
        }
        // POST: LoginCustomers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SerialNumber,AccountNumber,InternetBankingId,InternetBankingPassword")] LoginCustomer loginCustomer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(loginCustomer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(loginCustomer);
        }

        // GET: LoginCustomers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.LoginCustomer == null)
            {
                return NotFound();
            }

            var loginCustomer = await _context.LoginCustomer.FindAsync(id);
            if (loginCustomer == null)
            {
                return NotFound();
            }
            return View(loginCustomer);
        }

        // POST: LoginCustomers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SerialNumber,AccountNumber,InternetBankingId,InternetBankingPassword")] LoginCustomer loginCustomer)
        {
            if (id != loginCustomer.SerialNumber)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(loginCustomer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LoginCustomerExists(loginCustomer.SerialNumber))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(loginCustomer);
        }

        // GET: LoginCustomers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.LoginCustomer == null)
            {
                return NotFound();
            }

            var loginCustomer = await _context.LoginCustomer
                .FirstOrDefaultAsync(m => m.SerialNumber == id);
            if (loginCustomer == null)
            {
                return NotFound();
            }

            return View(loginCustomer);
        }

        // POST: LoginCustomers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.LoginCustomer == null)
            {
                return Problem("Entity set 'CustomerWebAppContext.LoginCustomer'  is null.");
            }
            var loginCustomer = await _context.LoginCustomer.FindAsync(id);
            if (loginCustomer != null)
            {
                _context.LoginCustomer.Remove(loginCustomer);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LoginCustomerExists(int id)
        {
          return _context.LoginCustomer.Any(e => e.SerialNumber == id);
        }

        [HttpGet]
        [Route("/LoginCustomers/LogOut")]
        public ActionResult LogOut()
        {
            TempData.Clear();
            return View("Create");
        }

    }
}

Bank_Apps/CustomerWebApp/Controllers/TransferMoneyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CustomerWebApp.Data;
using CustomerWebApp.Models;

namespace CustomerWebApp.Controllers
{
    public class TransferMoneyController : Controller
    {
        private readonly CustomerWebAppContext _context;
        private readonly BankAccountDBContext _AccountDetailscontext = new BankAccountDBContext();
        private double balance;

        public TransferMoneyController(CustomerWebAppContext context)
        {
            _context = context;
        }

        // GET: TransferMoney
        public async Task<IActionResult> Index()
        {
              return View(await _context.TransferMoney.ToListAsync());
        }
        private bool TransferMoneyExists(int id)
        {
          return _context.TransferMoney.Any(e => e.SerialNumber == id);
        }

        [HttpGet]
        [Route("/TransferMoney/TransferMoneyIntra")]
        public ActionResult TransferMoneyIntra()
        {
            int accNumber = Convert.ToInt32(TempData["AccountNumber"]);
            var loginCustomer1 = _context.LoginCustomer.FirstOrDefault(m => m.AccountNumber == accNumber);

            if (loginCustomer1 == null)
            {
                return NotFound();
            }
            else
            {
                accNumber = loginCustomer1.AccountNumber;
            }
            TempData["AccountNumber"] = _AccountDetailscontext.BankBalanceClasses.Where(j => j.AccountNumber == loginCustomer1.AccountNumber).FirstOrDefault().AccountNumber.ToString();
            TempData["BankBalance"] = _AccountDetailscontext.BankBalanceClasses.Where(j => j.AccountNumber == loginCustomer1.AccountNumber).FirstOrDefault().Balance.ToString();

            return View("TransferMoneyIntra");

        }



        [HttpPost]
        [Route("/TransferMoney/TransferProcessing")]
        public ActionResult TransferProcessing([Bind("SerialNumber,FromAccountNumber,ToAccountNumber,Amount,TransactionId")] TransferMoney transfer)
        {
            int accNumber = Convert.ToInt32(TempData["AccountNumber"]);
            TempData["AccountNumber"]=accNumber;
            int ToAccountNumber = transfer.ToAccountNumber;
            int Amount = transfer.Amount;
            int SerNo = transfer.SerialNumber;
            int FromAccNumber = transfer.FromAccountNumber;

            string dateTime = DateTime.Now.ToString("G");
            string dateTimeInt = dateTime.Replace(@" ", String.Empty).Replace(@":", String.Empty).Replace(@"-", String.Empty);
            string transactionID = dateTimeInt + accNumber;

            transfer.TransactionId=transactionID;
            transfer.FromAccountNumber = accNumber;
            _context.TransferMoney.Add(transfer);
            _context.SaveChanges();

            var fromAccount = _AccountDetailscontext.BankBalanceClasses.Where(j => j.AccountNumber == accNumber).FirstOrDefault();
            fromAccount.Balance-=Amount;

            var toAccount = _AccountDetailscontext.BankBalanceClasses.Where(j => j.AccountNumber == ToAccountNumber).FirstOrDefault();
            toAccount.Balance += Amount;
            _AccountDetailscontext.SaveChanges();

            return View("TransferStatus");
        }

    }
}

Bank_Apps/CustomerWebApp/Views/TransferMoney/Create.cshtml
@model CustomerWebApp.Models.TransferMoney

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TransferMoney</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FromAccountNumber" class="control-label"></label>
                <input asp-for="FromAccountNumber" class="form-control" />
                <span asp-validation-for="FromAccountNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ToAccountNumber" class="control-label"></label>
                <input asp-for="ToAccountNumber" class="form-control" />
                <span asp-validation-for="ToAccountNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TransactionId" class="control-label"></label>
                <input asp-for="TransactionId" class="form-control" />
                <span asp-validation-for="TransactionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Bank_Apps/CustomerWebApp/Views/TransferMoney/TransferMoneyIntra.cshtml
@model CustomerWebApp.Models.TransferMoney

<h4>Transfer Money To other ABC Accounts</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="TransferProcessing">
            <div asp-validation-summary="ModelOnly" class="text-danger" ></div>
            <div class="form-group">
                <label asp-for="FromAccountNumber" class="control-label">Enter Receipient Account Number</label>
                <input asp-for="FromAccountNumber" class="form-control" />
                <span asp-validation-for="FromAccountNumber" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="ToAccountNumber" class="control-label">Enter Receipient Account Number Again</label>
                <input asp-for="ToAccountNumber" class="form-control" />
                <span asp-validation-for="ToAccountNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Transfer Money" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br />

<div>
    <a asp-action="LogOut" asp-controller="LoginCustomers">Cancel Transaction</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Bank_Apps/CustomerWebApp/Views/TransferMoney/TransferStatus.cshtml
@model CustomerWebApp.Models.TransferMoney

<h2>Transfer Money To other ABC Accounts</h2>
<hr />
<h4> Success!!! Money Transferred</h4>


<div>
    <a asp-action="TransferMoneyIntra" asp-controller="TransferMoney">Do Another Transaction</a> <br />
    <a asp-action="LogOut" asp-controller="LoginCustomers">LogOut</a> <br />
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}