Bank_Apps/CustomerWebApp/Models/LoginCustomer.cs
using System.ComponentModel.DataAnnotations;
namespace CustomerWebApp.Models
{
    public class LoginCustomer
    {

        [Key]
        public int SerialNumber { get; set; }
        public int AccountNumber { get; set; }
        public int InternetBankingId { get; set; }
        public string InternetBankingPassword { get; set; }

        public LoginCustomer()
        {

        }
    }
}

Bank_Apps/CustomerWebApp/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CustomerWebApp.Data;
using CustomerWebApp.Models;

namespace CustomerWebApp.Controllers
{
    public class AccountsController : Controller
    {
        private readonly CustomerWebAppContext _context;
        private readonly BankAccountDBContext _AccountDetailscontext = new BankAccountDBContext();
        private double balance;

        public AccountsController(CustomerWebAppContext context)
        {
            _context = context;
        }

        // GET: Accounts
        public async Task<IActionResult> Index()
        {
              return View(await _context.Account.ToListAsync());
        }

        // GET: Accounts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Account == null)
            {
                return NotFound();
            }

            var account = await _context.Account
                .FirstOrDefaultAsync(m => m.AccountNumber == id);
            if (account == null)
            {
                return NotFound();
            }

            return View(account);
        }

        // GET: Accounts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Accounts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AccountNumber,FirstName,LastName,Ifsc,AccountSummary,AadharNumber,MobileNumber")] Account account)
        {
            if (ModelState.IsValid)
            {
                _context.Add(account);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(account);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GetBankBalance([Bind("AccountNumber", "FirstName", "LastName", "Ifsc", "MobileNumber")] Account loginCustomer)
        {
            //int accNumber = 0;
            //int accNum = loginCustomer.AccountNumber;
            int accNumber = Convert.ToInt32(TempData["AccountNumber"]);
            TempData["AccountNumber"] = accNumber.ToString();

            var loginCustomer1 = await _context.LoginCustomer
                .FirstOrDefaultAsync(m => m.AccountNumber == accNumber);

            if (loginCustomer1 == null)
            {
                return NotFound();
            }
            else
            {
                accNumber = loginCustomer1.AccountNumber;
            }

            TempData["BankBalance"] = _AccountDetailscontext.BankBalanceClasses.Where(j => j.AccountNumber == loginCustomer1.AccountNumber).FirstOrDefault().Balance.ToString();

            return View("GetBankBalance", _AccountDetailscontext.Accounts.Where(j => j.AccountNumber == loginCustomer1.AccountNumber).FirstOrDefault());
            //return View("FindAccountNumber",await _context.Account.Where(j=> j.AccountNumber == loginCustomer1.AccountNumber).ToListAsync());

        }
        
        private bool AccountExists(int id)
        {
          return _context.Account.Any(e => e.AccountNumber == id);
        }

        [HttpGet]
        [Route("/Accounts/TransferMoneyIntra/{id}")]
        public ActionResult TransferMoneyIntra(string id)
        {
            //int accNumber = 0;
            //int accNum = loginCustomer.AccountNumber;
            int accNumber = Convert.ToInt32(TempData["AccountNumber"]);

            var loginCustomer1 = _context.LoginCustomer.FirstOrDefault(m => m.AccountNumber == accNumber);

            if (loginCustomer1 == null)
            {
                return NotFound();
            }
            else
            {
                accNumber = loginCustomer1.AccountNumber;
            }
            TempData["AccountNumber"] = _AccountDetailscontext.BankBalanceClasses.Where(j => j.AccountNumber == loginCustomer1.AccountNumber).FirstOrDefault().AccountNumber.ToString();
            TempData["BankBalance"] = _AccountDetailscontext.BankBalanceClasses.Where(j => j.AccountNumber == loginCustomer1.AccountNumber).FirstOrDefault().Balance.ToString();

            return View("", _AccountDetailscontext.Accounts.Where(j => j.AccountNumber == loginCustomer1.AccountNumber).FirstOrDefault());
            //return View("FindAccountNumber",await _context.Account.Where(j=> j.AccountNumber == loginCustomer1.AccountNumber).ToListAsync());

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> FindAccount([Bind("SerialNumber,AccountNumber,InternetBankingId,InternetBankingPassword")] LoginCustomer loginCustomer)
        {
            int accNumber = 0;
            //if (id == 0 || _context.LoginCustomer == null)
            //{
            //    return NotFound();
            //}
            int id = loginCustomer.InternetBankingId;
            string password = loginCustomer.InternetBankingPassword;

            var loginCustomer1 = await _context.LoginCustomer
                .FirstOrDefaultAsync(m => m.InternetBankingId == id && m.InternetBankingPassword == password);

            if (loginCustomer1 == null)
            {
                return NotFound();
            }
            else
            {
                TempData["AccountNumber"] = loginCustomer1.AccountNumber;
            }


            return View("FindAccountNumber", _AccountDetailscontext.Accounts.Where(j => j.AccountNumber == loginCustomer1.AccountNumber).FirstOrDefault());
            //return View("FindAccountNumber",await _context.Account.Where(j=> j.AccountNumber == loginCustomer1.AccountNumber).ToListAsync());

        }
        [HttpGet]
        [Route("/Accounts/AccountPage")]
        public ActionResult AccountPage()
        {
            int accNumber = Convert.ToInt32(TempData["AccountNumber"]);
            TempData["AccountNumber"] = accNumber;
            return View("FindAccountNumber", _AccountDetailscontext.Accounts.Where(j => j.AccountNumber == accNumber).FirstOrDefault());
        }
    }
}

Bank_Apps/CustomerWebApp/Controllers/TransferMoneyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CustomerWebApp.Data;
using CustomerWebApp.Models;

namespace CustomerWebApp.Controllers
{
    public class TransferMoneyController : Controller
    {
        private readonly CustomerWebAppContext _context;
        private readonly BankAccountDBContext _AccountDetailscontext = new BankAccountDBContext();
        private double balance;

        public TransferMoneyController(CustomerWebAppContext context)
        {
            _context = context;
        }

        // GET: TransferMoney
        public async Task<IActionResult> Index()
        {
              return View(await _context.TransferMoney.ToListAsync());
        }
        private bool TransferMoneyExists(int id)
        {
          return _context.TransferMoney.Any(e => e.SerialNumber == id);
        }

        [HttpGet]
        [Route("/TransferMoney/TransferMoneyIntra")]
        public ActionResult TransferMoneyIntra()
        {
            int accNumber = Convert.ToInt32(TempData["AccountNumber"]);
            var loginCustomer1 = _context.LoginCustomer.FirstOrDefault(m => m.AccountNumber == accNumber);

            if (loginCustomer1 == null)
            {
                return NotFound();
            }
            else
            {
                accNumber = loginCustomer1.AccountNumber;
            }
            TempData["AccountNumber"] = _AccountDetailscontext.BankBalanceClasses.Where(j => j.AccountNumber == loginCustomer1.AccountNumber).FirstOrDefault().AccountNumber.ToString();
            TempData["BankBalance"] = _AccountDetailscontext.BankBalanceClasses.Where(j => j.AccountNumber == loginCustomer1.AccountNumber).FirstOrDefault().Balance.ToString();

            return View("TransferMoneyIntra");

        }



        [HttpPost]
        [Route("/TransferMoney/TransferProcessing")]
        public ActionResult TransferProcessing([Bind("SerialNumber,FromAccountNumber,ToAccountNumber,Amount,TransactionId")] TransferMoney transfer)
        {
            int accNumber = Convert.ToInt32(TempData["AccountNumber"]);
            TempData["AccountNumber"]=accNumber;
            int ToAccountNumber = transfer.ToAccountNumber;
            int Amount = transfer.Amount;
            int SerNo = transfer.SerialNumber;
            int FromAccNumber = transfer.FromAccountNumber;

            string dateTime = DateTime.Now.ToString("G");
            string dateTimeInt = dateTime.Replace(@" ", String.Empty).Replace(@":", String.Empty).Replace(@"-", String.Empty);
            string transactionID = dateTimeInt + accNumber;

            transfer.TransactionId=transactionID;
            transfer.FromAccountNumber = accNumber;
            _context.TransferMoney.Add(transfer);
            _context.SaveChanges();

            var fromAccount = _AccountDetailscontext.BankBalanceClasses.Where(j => j.AccountNumber == accNumber).FirstOrDefault();
            fromAccount.Balance-=Amount;

            var toAccount = _AccountDetailscontext.BankBalanceClasses.Where(j => j.AccountNumber == ToAccountNumber).FirstOrDefault();
            toAccount.Balance += Amount;
            _AccountDetailscontext.SaveChanges();

            return View("TransferStatus");
        }

    }
}

Bank_Apps/CustomerWebApp/Views/LoginCustomers/Create.cshtml
@model CustomerWebApp.Models.LoginCustomer

@{
    ViewData["Title"] = "Login";
}

<h1>ABC Internet Banking</h1>

<h4>Customer Login</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="FindAccount" asp-controller="Accounts">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="InternetBankingId" class="control-label">User ID</label>
                <input asp-for="InternetBankingId" class="form-control" />
                <span asp-validation-for="InternetBankingId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InternetBankingPassword" class="control-label">Password</label>
                <input asp-for="InternetBankingPassword" class="form-control" />
                <span asp-validation-for="InternetBankingPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Log In" class="btn btn-primary" />
                <br />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Forgot Password</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Bank_Apps/CustomerWebApp/Views/LoginCustomers/FindAccountNumber.cshtml
@model CustomerWebApp.Models.Account

<div>
    <h2>  Welcome to ABC Internet Banking </h2>
    <h4>Hi @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ifsc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ifsc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MobileNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MobileNumber)
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="TransferMoney"  asp-action="TransferMoneyIntra">Transfer Money To ABC Accounts</a>
    <a asp-action="TransferMoneyOther">Transfer Money To Other Accounts</a>
    <a asp-action="Edit" asp-route-id="@Model?.AccountNumber">Edit</a> |
    <a asp-action="Index">Back to List</a>

    <form asp-action="TransferMoneyIntra" asp-controller="TransferMoney">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <span asp-validation-for="AccountNumber" class="text-danger"></span>
        </div>
        <div class="form-group">
            <br />
            <input type="submit" value="Transfer Money" class="btn btn-primary" />
        </div>
    </form>



    <form asp-action="GetBankBalance">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <span asp-validation-for="AccountNumber" class="text-danger"></span>
        </div>
        <div class="form-group">
            <br />
            <input type="submit" value="Check Balance" class="btn btn-primary" />
        </div>
    </form>

</div>

Bank_Apps/CustomerWebApp/Views/LoginCustomers/GetBankBalance.cshtml
@model CustomerWebApp.Models.Account

<div>
    <h2>  Welcome to ABC Internet Banking </h2>
    <h4>Hi @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ifsc)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ifsc)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MobileNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MobileNumber)
        </dd>
    </dl>
</div>
<div>
    <h4>Bank Balance: Rs @TempData["BankBalance"] </h4>
    <br />
    <a asp-action="Index">Back to List</a>
    <a asp-action="Edit" asp-route-id="@Model?.AccountNumber">Edit</a>
</div>

Bank_Apps/CustomerWebApp/Views/LoginCustomers/Index.cshtml
@model IEnumerable<CustomerWebApp.Models.LoginCustomer>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AccountNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InternetBankingId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InternetBankingPassword)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AccountNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InternetBankingId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InternetBankingPassword)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.SerialNumber">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.SerialNumber">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.SerialNumber">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>